name: hit_fast_food
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: '^1.0.9'
  smooth_star_rating: '1.0.2'
  fluttertoast: ^3.1.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class. PERI-PERI WINGS X6
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # burger
   - images/CHEESE BURGER1500.jpg
   - images/HAMBURGER 1000.jpg
   - images/CHICKEN BURGER.jpg
   - images/COUNTRY BURGER.jpg
   - images/double CHEESE BURGER.jpg
   - images/HIT BURGER.jpg
   - images/SMOKED CHICKEN Burger.jpg
   - images/VEGGIE BURGER.jpg
  #  chicken
   - images/CRUSTY CHICKEN X4.jpg
   - images/CRUSTY CHICKEN X10.jpg 
   - images/CRUSTY WINGS X6.jpg 
   - images/CRUSTY WINGS X10.jpg 
   - images/PERI-PERI CHICKEN X4.jpg
   - images/PERI-PERI CHICKEN X10.jpg
   - images/PERI-PERI WINGS X6.jpg
   - images/PERI-PERI WINGS X10.jpg
  #  tacos
   - images/tacos taille S.jpg
   - images/tacos taille M.jpg
   - images/tacos taille L.jpg
  # hot dog et sandwich
   - images/HOT DOG POULET.jpg
   - images/HOT DOG Boeuf.jpg
   - images/Sandwichs KOFTA.jpg
  # Grillade et platter 
   - images/STEAK FRITES.jpg
   - images/BROCHETTES.jpg
   - images/MIX GRILLED.jpg
  # Salades 
   - images/salades de CREVETTES.jpg
   - images/salade de poulet.jpg
  # Boisson 
   - images/smoothie.jpg
   - images/smoothie detox.jpg
   - images/soda ice cream.jpg
   - images/milkshake.jpg
   
  # cat
   - images/boissonCat.jpg
   - images/burgerCat.jpg
   - images/chickenCat.jpg
   - images/extraCat.jpg
   - images/grillCat.jpg
   - images/hotdogCat.jpg
   - images/saladCat.jpg
   - images/sandwichCat.jpg
   - images/tacosCat.jpg
   - images/gourmanCat.jpg
   - images/drawerimag.jpg
   - images/logoSpl.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Fryo
      fonts:
        - asset: fonts/Fryo.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family:  CenturyGothic
      fonts:
        - asset: fonts/CenturyGothicRegular.ttf
        - asset: fonts/CenturyGothicBold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
